export const LOAD_ASSETS_SUCCESS ='LOAD_ASSETS_SUCCESS';
export const UPLOAD_FILE_SET ='UPLOAD_FILE_SET';
export const UPLOAD_ASSETS_SUCCESS ='UPLOAD_ASSETS_SUCCESS';
export const TOTAL_ASSETS ='TOTAL_ASSETS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';